name: DevOps CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  run-python-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Execute app.py
        run: python app.py
